const express = require('express')
const path = require('path')
require('dotenv').config()
const db = require('./models')
const app = express()
const roleRoutes = require('./routes/role-routes')
const userRoutes = require('./routes/user-routes')
const refereeRoutes = require('./routes/referee-routes')
const courtRoutes = require('./routes/court-routes')
const workoutAndTestRoutes = require('./routes/workoutAndTest-routes')
const testResultRoutes = require('./routes/testResult-routes')
const teamRoutes = require('./routes/team-routes')
const playerRoutes = require('./routes/player-routes')
const degreeRoutes = require('./routes/Degree-routes')
const matchRoutes = require('./routes/match-routes')
const matchTeamsRoutes = require('./routes/matchTeams-routes')
const assignmentRoutes = require('./routes/assignment-routes')
const adminRoutes = require('./routes/admin-routes')
const authRoutes = require('./routes/auth-routes')
const eventRoutes = require('./routes/event-routes')
const typeOfEventRoutes = require('./routes/typeOfEvent-routes')
const lineUpRoutes = require('./routes/lineUp-routes')
const refereeEvaluationRoutes = require('./routes/refereeEvaluation-routes')
const matchReportRoutes = require('./routes/matchReport-routes')
const { FORCE } = require('sequelize/lib/index-hints')
const cors = require('cors')
 
app.use(cors({ origin: ["http://localhost:3000", "http://localhost:3001"],
  credentials: true}))
app.use(express.urlencoded({extended:true}))
app.use(express.json())

// serve uploaded files (e.g., images) from /uploads
app.use('/uploads', express.static(path.join(__dirname, 'uploads')))

app.use('/api/role',roleRoutes)
app.use('/api/user',userRoutes)
app.use('/api/referee',refereeRoutes)
app.use('/api/court',courtRoutes)
app.use('/api/workoutAndTest',workoutAndTestRoutes)
app.use('/api/testResult',testResultRoutes)
app.use('/api/team',teamRoutes)
app.use('/api/degree',degreeRoutes)
app.use('/api/match',matchRoutes)
app.use('/api/matchTeams',matchTeamsRoutes)
app.use('/api/assignment',assignmentRoutes)
app.use('/api/auth', authRoutes)
app.use('/api/admin', adminRoutes)
app.use('/api/typeOfEvent', typeOfEventRoutes)
app.use('/api/player', playerRoutes)
app.use('/api/matchReport', matchReportRoutes)
app.use('/api/lineUp', lineUpRoutes)
app.use('/api/refereeEvaluation', refereeEvaluationRoutes)
app.use('/api/event', eventRoutes)

db.sequelize.sync({ force: true }).then(async () => {

    app.listen(3000, () => console.log('server listening in port 3000'))
})